services:
    doctoubib_models.doctors:
        class: Doctoubib\ModelsBundle\Entity\Doctor
        arguments: ["@doctrine.orm.entity_manager"]

    doctoubib_models.contactmessage.repository:
        class: Doctoubib\ModelsBundle\Repository\ContactMessageRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [Doctoubib\ModelsBundle\Entity\ContactMessage]

    doctoubib_models.contactmessage:
        class: Doctoubib\ModelsBundle\Service\ContactMessageService
        arguments: ["@doctoubib_models.contactmessage.repository"]

    doctoubib_models.sponsorship.repository:
        class: Doctoubib\ModelsBundle\Repository\SponsorshipRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [Doctoubib\ModelsBundle\Entity\Sponsorship]

    doctoubib_models.sponsorship:
        class: Doctoubib\ModelsBundle\Service\SponsorshipService
        arguments: ["@doctoubib_models.sponsorship.repository"]
