<?php

namespace Doctoubib\ModelsBundle\Repository;

/**
 * DoctorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctorRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByCriteria($filters)
    {
        $qb = $this->createQueryBuilder('d');

        if (!empty($filters['region'])) {
            $qb->leftJoin('d.specialities', 's')
                ->where('s.slug = :speciality');
            if (!empty($filters['region'])) {
                $qb->leftJoin('d.offices', 'o')
                    ->leftJoin('o.region', 'r')
                    ->andWhere('r.slug = :region')
                    ->setParameter('region', $filters['region']);
            }
        }
        
        if (!empty($filters['speciality'])) {
              $qb->andWhere('d.enabled = :enabled')
                ->andWhere('d.isVisible = :visible')
                ->setParameter('enabled', 1)
                ->setParameter('visible', 1)
                ->setParameter('speciality', $filters['speciality']);
        }

        return $qb->getQuery()->getResult();
     }

    /**
     * @param $letter
     *
     * @return array
     */
    public function findByLetter($letter)
    {
        $qb = $this->createQueryBuilder('d')
            ->where('d.lastname LIKE :lastanme_first_letter')
            ->andWhere('d.enabled = :enabled')
            ->andWhere('d.isVisible = :visible')
            ->setParameter('enabled', 1)
            ->setParameter('visible', 1)
            ->setParameter('lastanme_first_letter', $letter.'%');

        return $qb->getQuery()->getResult();
    }
}




