<?php

namespace Doctoubib\ModelsBundle\Repository;

/**
 * DoctorFeesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctorFeesRepository extends \Doctrine\ORM\EntityRepository
{
}
