<?php

namespace Doctoubib\ModelsBundle\Repository;

/**
 * DoctorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctorRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByCriteria($filters)
    {
        if (!empty($filters['slug'])) {
           return $this->findOneBy(['slug' => $filters['slug']]);
        } elseif (!empty($filters['speciality'])) {
            $qb = $this->createQueryBuilder('d')
                ->leftJoin('d.specialities', 's')
                ->where('s.slug = :speciality')
                ->setParameter('speciality', $filters['speciality']);

            if (!empty($filters['region'])) {
                $qb->leftJoin('d.region', 'r')
                    ->andWhere('r.slug = :region')
                    ->setParameter('region', $filters['region']);
            }

            return $qb->getQuery()->getResult();
        } elseif (!empty($filters['lastanme_first_letter'])) {
            $qb = $this->createQueryBuilder('d')
                ->where('d.lastname LIKE :lastanme_first_letter')
                ->setParameter('lastanme_first_letter', $filters['lastanme_first_letter'].'%');

            return $qb->getQuery()->getResult();
        }
     }
}
