<?php

namespace Doctoubib\ModelsBundle\Repository;

/**
 * ParkingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParkingRepository extends \Doctrine\ORM\EntityRepository
{
}
