<?php

namespace Doctoubib\ModelsBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    function findByCategories($categories)
    {

        $qb    = $this->createQueryBuilder('p');
        $query = $qb
            ->select('p')
            ->leftJoin('p.categories', 'c')
            ->addSelect('c')
            ->add('where', $qb->expr()->in('c', ':c'))
            ->setParameter('c', $categories)
            ->getQuery();

        return $query->getResult();
    }
}
