<?php

namespace Doctoubib\ModelsBundle\Repository;

/**
 * PricingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricingRepository extends \Doctrine\ORM\EntityRepository
{
}
