<?php

namespace Doctoubib\ModelsBundle\Repository;
use Doctoubib\ModelsBundle\Entity\Sponsorship;

/**
 * SponsorshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsorshipRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(Sponsorship $sponsorship)
    {
        $this->_em->persist($sponsorship);
        $this->_em->flush();
    }
}
